imports and parsing through

In [1]:
import pandas as pd
import glob
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

files = sorted(glob.glob("data/**/*.xlsx", recursive=True))
print(f"Found {len(files)} files:\n")
for f in files:
    print(f)

Found 21 files:

data/2018/2018 TARIFAS Y COLABORADORAS CON Y SIN IVA.xlsx
data/2019/2019 TARIFA COLABORADORAS v1.xlsx
data/2019/2019 TARIFA USUARIOS Y SOCIOS v2.xlsx
data/2020/2020 IMPRESO CANINAS V2020.xlsx
data/2020/2020_TARIFAS.xlsx
data/2021/2021 ESTUDIO MODIFICACION TARIFAS (NO HAY MÁS).xlsx
data/2021/2021_TARIFAS.xlsx
data/2022/2022 IMPRESO COLABORADORAS V2022_3.xlsx
data/2022/2022_TARIFAS_V1_1_Ago.xlsx
data/2022/2022_TARIFAS_V1_Feb.xlsx
data/2022/2022_TARIFAS_V3_Oct.xlsx
data/2023/2023 IMPRESO COLABORADORAS V2023_1.xlsx
data/2023/2023_TARIFAS.xlsx
data/2024/2024 IMPRESO COLABORADORAS V3.xlsx
data/2024/2024_TARIFAS.xlsx
data/2025/2025 IMPRESO COLABORADORAS v2.xlsx
data/2025/2025 IMPRESO COLABORADORAS v4.xlsx
data/2025/2025_TARIFAS_V3_Ene.xlsx
data/2025/2025_TARIFAS_V4_Sept.xlsx
data/2026/2026 IMPRESO COLABORADORAS v3.xlsx
data/2026/2026 TARIFAS V2.xlsx

2018

In [2]:
df = pd.read_excel("data/2018/2018 TARIFAS Y COLABORADORAS CON Y SIN IVA.xlsx", header=None)
df.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11
0,2018,CON IVA,NaN,NaN,NaN,SIN I.V.A.,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,0.21,NaN,NaN,NaN,NaN,NaN
2,NaN,Socios,Usuario,Colaboradoras,NaN,Socios,Usuario,Colaboradoras,NaN,Usuario,Colaboradoras,Colaboradoras
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUMENTO RESPECTO SOCIOS,VARIACION RESPECTO SOCIOS,VARIACION RESPECTO USUARIO
4,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,PEDIGREE CON TRANSFERENCIA TRES GENERACIONES,29.3,43.2,25.056,NaN,24.214876,35.702479,20.707438,NaN,0.474403,-0.144846,-0.42
6,PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.),33.1,48.7,28.27035,NaN,27.355372,40.247934,23.363926,NaN,0.471299,-0.145911,-0.4195
7,PEDIGREE PARA PERROS INSCRITOS EN EL R.R.C. (sin genealógica completa),17,25,14.5025,NaN,14.049587,20.661157,11.985537,NaN,0.470588,-0.146912,-0.4199
8,PEDIGREE DE EXPORTACIÓN TRES GENERACIONES,56.5,56.5,38.05275,NaN,46.694215,46.694215,31.448554,NaN,0,-0.3265,-0.3265
9,PEDIGREE DE EXPORTACIÓN CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.),62.1,62.1,41.58216,NaN,51.322314,51.322314,34.365421,NaN,0,-0.3304,-0.3304
10,PEDIGREE SIN TRANSFERENCIA,26.3,36.3,20.98866,NaN,21.735537,30,17.346,NaN,0.380228,-0.201952,-0.4218
11,PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.),30,41.3,22.22353,NaN,24.793388,34.132231,18.366554,NaN,0.376667,-0.259216,-0.4619
12,DUPLICADO DE PEDIGREE TRES GENERACIONES,26.3,36.3,20.98866,NaN,21.735537,30,17.346,NaN,0.380228,-0.201952,-0.4218
13,DUPLICADO DE PEDIGREE CUATRO GENERACIONES,30,41.3,22.22353,NaN,24.793388,34.132231,18.366554,NaN,0.376667,-0.259216,-0.4619
14,DUPLICADO EXPORT PEDIGREE TRES GENERACIONES,50.9,50.9,34.28115,NaN,42.066116,42.066116,28.331529,NaN,0,-0.3265,-0.3265

In [5]:
df = pd.read_excel("data/2018/2018 IMPRESO CANINAS.xlsm", header=None)
df.head(10)

,0,1,2,3,4,5,6,7,8,9
0,NaN,SOCIEDAD CANINA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,FECHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,CONCEPTO,NaN,NaN,NaN,CÓDIGO,CANTIDAD,PRECIO,NaN,IMPORTE
4,PEDIGREES Y TRANSFERENCIA DE PROPIEDAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,PEDIGREE CON TRANSFERENCIA TRES GENERACIONES,NaN,NaN,NaN,0001,NaN,20.71,NaN,0
6,NaN,PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES (SI CONSTAN EN EL L.O.E.),NaN,NaN,NaN,0002,NaN,23.36,NaN,0
7,NaN,PEDIGREE PARA PERROS INSCRITOS EN EL R.R.C. (SIN GENEALOGIA COMPLETA),NaN,NaN,NaN,0003,NaN,11.99,NaN,0
8,NaN,PEDIGREE DE EXPORTACION (3 generaciones),NaN,NaN,NaN,0004,NaN,31.45,NaN,0
9,NaN,PEDIGREE DE EXPORTACION (4 generaciones),NaN,NaN,NaN,0005,NaN,34.37,NaN,0

2019

In [7]:
df = pd.read_excel("data/2019/2019 TARIFA COLABORADORAS v1.xlsx", header=None)
df.head(10)

,0,1,2,3,4,5,6,7
0,SOCIEDAD CANINA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,FECHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CONCEPTO,NaN,NaN,CÓDIGO,CANTIDAD,PRECIO,NaN,IMPORTE
4,PEDIGREES Y TRANSFERENCIA DE PROPIEDAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,PEDIGREE CON TRANSFERENCIA TRES GENERACIONES,NaN,NaN,0001,NaN,21.19,NaN,0
6,PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES (si consta en el L.O.E..),NaN,NaN,0002,NaN,23.94,NaN,0
7,PEDIGREE PARA PERROS INSCRITOS EN EL R.R.C. (sin genealogía completa),NaN,NaN,0003,NaN,12.28,NaN,0
8,PEDIGREE DE EXPORTACION (3 generaciones),NaN,NaN,0004,NaN,32.17,NaN,0
9,PEDIGREE DE EXPORTACION (4 generaciones),NaN,NaN,0005,NaN,35.2,NaN,0

In [12]:
df = pd.read_excel("data/2019/2019 TARIFA USUARIOS Y SOCIOS v2.xlsx")
df.head(15)

,Unnamed: 0,REAL SOCIEDAD CANINA DE ESPAÑA,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,Declarada de Utilidad Pública por Real Orden del Ministerio de Fomento de 27-02-1918,NaN,NaN,NaN,NaN,NaN
1,NaN,Miembro de la Fédération Cynologique Internacionale (FCI) desde 1912,NaN,NaN,NaN,NaN,NaN
2,NaN,"Calle Maldonado, 56 - 28006 Madrid",NaN,NaN,NaN,NaN,NaN
3,NaN,( 91-426 49 60 -- : www.rsce.es -- * administracion@rsce.es,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,TARIFA GENERAL DE PRECIOS,NaN,NaN,NaN,NaN,NaN,NaN
6,(en vigor a partir del día 1 de enero de 2019),NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,El pago de los trámites podrá realizarse mediante transferencia bancaria realizada a la siguiente cuenta:,NaN,NaN,NaN,NaN,NaN,NaN
9,TITULAR,NaN,NaN,NaN,REAL SOCIEDAD CANINA DE ESPAÑA,NaN,NaN
10,ENTIDAD,NaN,NaN,NaN,BANCO SANTANDER,NaN,NaN
11,NÚMERO DE CUENTA,NaN,NaN,NaN,ES32 0030 8269 3800 0027 4271,NaN,NaN
12,CÓDIGO BIC (para pagos desde el extranjero),NaN,NaN,NaN,BSCHESMM,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,TRÁMITES,NaN,NaN,NaN,NaN,Socios de la RSCE,Resto de usuarios de la RSCE

2020

In [ ]:
df = pd.read_excel("data/2020/2020 IMPRESO CANINAS V2020.xlsx")
df.head(15)

,SOCIEDAD CANINA,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,FECHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,TARIFA AÑO 2020,NaN,NaN,NaN,NaN,NaN
2,CONCEPTO,NaN,NaN,CÓDIGO,CANTIDAD,PRECIO,NaN,IMPORTE
3,PEDIGREES Y TRANSFERENCIA DE PROPIEDAD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PEDIGREE CON TRANSFERENCIA TRES GENERACIONES,NaN,NaN,0001,NaN,21.62,NaN,0
5,PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES (SI CONSTAN EN EL L.O.E.),NaN,NaN,0002,NaN,24.42,NaN,0
6,PEDIGREE PARA PERROS INSCRITOS EN EL R.R.C. (SIN GENEALOGIA COMPLETA),NaN,NaN,0003,NaN,12.57,NaN,0
7,PEDIGREE DE EXPORTACION (3 generaciones),NaN,NaN,0004,NaN,32.84,NaN,0
8,PEDIGREE DE EXPORTACION (4 generaciones),NaN,NaN,0005,NaN,35.92,NaN,0
9,PEDIGREE SIN TRANSFERENCIA,NaN,NaN,0006,NaN,18.16,NaN,0
10,PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES (SI CONSTAN EN EL L.O.E.),NaN,NaN,0007,NaN,19.21,NaN,0
11,DUPLICADO DE PEDIGREE TRES GENERACIONES,NaN,NaN,0008,NaN,18.16,NaN,0
12,DUPLICADO DE PEDIGREE CUATRO GENERACIONES,NaN,NaN,0009,NaN,19.21,NaN,0
13,DUPLICADO EXPORT PEDIGREE TRES GENERACIONES,NaN,NaN,0010,NaN,29.61,NaN,0
14,DUPLICADO EXPORT PEDIGREE CUATRO GENERACIONES,NaN,NaN,0011,NaN,32.16,NaN,0

In [14]:
df = pd.read_excel("data/2020/2020_TARIFAS.xlsx")
df.head(15)

,Categoría,Trámite,Socios de la RSCE (€),Resto usuarios de la RSCE (€),Notas
0,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,PEDIGREE CON TRANSFERENCIA TRES GENERACIONES,30.6,45.1,NaN
1,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del LOE),34.6,50.9,NaN
2,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,PEDIGREE PARA PERROS INSCRITOS EN EL RRC (sin genealógica completa),17.8,26.2,NaN
3,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,PEDIGREE DE EXPORTACIÓN TRES GENERACIONES,59.0,59.0,Precio único
4,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,PEDIGREE DE EXPORTACIÓN CUATRO GENERACIONES (si la genealogía consta en la base de datos del LOE),64.9,64.9,Precio único
5,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,PEDIGREE SIN TRANSFERENCIA,27.6,38.0,NaN
6,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del LOE),31.4,43.2,NaN
7,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,DUPLICADO DE PEDIGREE TRES GENERACIONES,27.6,38.0,NaN
8,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,DUPLICADO DE PEDIGREE CUATRO GENERACIONES,31.4,43.2,NaN
9,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,DUPLICADO EXPORT PEDIGREE TRES GENERACIONES,53.2,53.2,Precio único
10,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,DUPLICADO EXPORT PEDIGREE CUATRO GENERACIONES,58.3,58.3,Precio único
11,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,"TRANSFERENCIA DE PROPIEDAD EN PEDIGREE, REGISTRO INICIAL O PERRO IMPORTADO",11.6,14.0,NaN
12,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,CESIÓN TEMPORAL DE PROPIEDAD DE LA HEMBRA REPRODUCTORA,17.3,20.9,NaN
13,INSCRIPCIONES EN EL LOE / RRC,INSCRIPCIÓN IMPORTADOS,27.0,39.7,NaN
14,INSCRIPCIONES EN EL LOE / RRC,INSCRIPCIÓN PERROS DE OTROS LIBROS GENEALÓGICOS,57.3,59.0,Este trámite no admite plus de urgencia

In [16]:
df = pd.read_excel("data/2021/2021 ESTUDIO MODIFICACION TARIFAS (NO HAY MÁS).xlsx")
df.head(15)

,Unnamed: 0,año,2020,Unnamed: 3,Unnamed: 4,propuesta año,Unnamed: 6,2021,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,Socios de la RSCE,Resto usuarios de la RSCE,Caninas sin IVA,NaN,Socios de la RSCE,Resto usuarios de la RSCE,Caninas sin IVA,NaN,NaN,NaN,NaN,NaN,Margen Colaboradoras,NaN,NaN
1,PEDIGREES Y TRANSFERENCIAS DE PROPIEDAD,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,2020.0,NaN,2021.000000,NaN
2,PEDIGREE CON TRANSFERENCIA TRES GENERACIONES,30.6,45.1,21.621471,NaN,30.6,45.1,21.621471,NaN,0.0,0.0,0.0,NaN,0.479412,0.479412,OK
3,PEDIGREE CON TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.),34.6,50.9,24.41976,NaN,34.6,50.9,24.41976,NaN,0.0,0.0,0.0,NaN,0.47976,0.479760,OK
4,PEDIGREE PARA PERROS INSCRITOS EN EL R.R.C. (sin genealógica completa),17.8,26.2,12.567813,NaN,17.8,26.2,12.567812,NaN,0.0,0.0,0.0,NaN,0.479687,0.479687,OK
5,PEDIGREE DE EXPORTACIÓN TRES GENERACIONES,59,0,32.824305,NaN,59,0,32.824305,NaN,0.0,NaN,0.0,NaN,0.556344,0.556344,OK
6,PEDIGREE DE EXPORTACIÓN CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.),64.9,0,35.905085,NaN,64.9,0,35.905085,NaN,0.0,NaN,0.0,NaN,0.553237,0.553237,OK
7,PEDIGREE SIN TRANSFERENCIA,27.6,38,18.162366,NaN,27.6,38,18.162366,NaN,0.0,0.0,0.0,NaN,0.477957,0.477957,OK
8,PEDIGREE SIN TRANSFERENCIA CUATRO GENERACIONES (si la genealogía consta en la base de datos del L.O.E.),31.4,43.2,19.210213,NaN,31.4,43.2,19.210213,NaN,0.0,0.0,0.0,NaN,0.444681,0.444681,OK
9,DUPLICADO DE PEDIGREE TRES GENERACIONES,27.6,38,18.162366,NaN,27.6,38,18.162366,NaN,0.0,0.0,0.0,NaN,0.477957,0.477957,OK
10,DUPLICADO DE PEDIGREE CUATRO GENERACIONES,31.4,43.2,19.210213,NaN,31.4,43.2,19.210213,NaN,0.0,0.0,0.0,NaN,0.444681,0.444681,OK
11,DUPLICADO EXPORT PEDIGREE TRES GENERACIONES,53.2,0,29.599624,NaN,53.2,0,29.599624,NaN,0.0,NaN,0.0,NaN,0.556384,0.556384,OK
12,DUPLICADO EXPORT PEDIGREE CUATRO GENERACIONES,58.3,0,32.14837,NaN,58.3,0,32.14837,NaN,0.0,NaN,0.0,NaN,0.55143,0.551430,OK
13,"TRANSFERENCIA DE PROPIEDAD EN PEDIGREE, REGISTRO INICIAL O PERRO IMPORTADO",11.6,14,6.744526,NaN,11.6,14,6.744526,NaN,0.0,0.0,0.0,NaN,0.481752,0.481752,OK
14,CESIÓN TEMPORAL DE PROPIEDAD DE LOS REPRODUCTORES,17.3,20.9,9.999216,NaN,17.3,20.9,9.999216,NaN,0.0,0.0,0.0,NaN,0.478431,0.478431,OK

In [17]:
df = pd.read_excel("data/2021/2021_TARIFAS.xlsx")
df.head(15)

,Categoría,Trámite,Socios de la RSCE (€),Resto usuarios de la RSCE (€),Notas
0,INSCRIPCIONES,REGISTRO INICIAL DE RAZA,41.9,41.9,Precio único
1,INSCRIPCIONES,REGISTRO INICIAL GRUPO ÉTNICO,25.0,25.0,Precio único
2,INSCRIPCIONES,IMPRESO ALTA DE CAMADA,2.1,2.1,Precio único
3,INSCRIPCIONES,FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento),2.7,4.3,NaN
4,INSCRIPCIONES,INSCRIPCIÓN CACHORRO,14.9,18.0,NaN
5,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 6 meses y menos de 9 meses de edad,14.9,18.0,NaN
6,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 9 meses y menos de 12 meses de edad,29.8,36.0,NaN
7,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 12 meses y menos de 18 meses de edad,44.7,53.9,NaN
8,INSCRIPCIONES,INSCRIPCIÓN PERRO con más de 18 meses aportando prueba ADN progenitores y huella genética de compatibilidad,89.4,108.0,"Tramitación exclusiva oficinas RSCE, requiere autorización Comisión Libro de Orígenes Español"
9,INSCRIPCIONES,INSCRIPCIÓN IMPORTADOS,27.0,39.7,NaN
10,INSCRIPCIONES,INSCRIPCIÓN PERROS DE OTROS LIBROS GENEALÓGICOS,57.3,59.0,Este trámite no admite plus de urgencia
11,INSCRIPCIONES,DUPLICADO JUSTIFICANTE DE INSCRIPCIÓN,4.5,6.2,NaN
12,INSCRIPCIONES,BAJA DE UN PERRO EN EL LOE/RRC (para su posterior inscripción de otros libros genealógicos),27.0,39.7,NaN
13,INSCRIPCIONES,CONFIRMACIÓN DE RAZA (perros de razas españolas),5.1,5.1,Precio único
14,PEDIGRÍES Y TRANSFERENCIAS DE PROPIEDAD,PEDIGREE CON TRANSFERENCIA TRES GENERACIONES,30.6,45.1,NaN

2022

In [18]:
df = pd.read_excel("data/2022/2022 IMPRESO COLABORADORAS V2022_3.xlsx")
df.head(15)

,SOCIEDAD CANINA,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,FECHA,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,TARIFA AÑO 2022,NaN,NaN,NaN,NaN
2,CONCEPTO,NaN,NaN,CÓDIGO,CANTIDAD,PRECIO,IMPORTE
3,INCRIPCIONES EN EL L.O.E./R.R.C.,NaN,NaN,NaN,NaN,NaN,NaN
4,REGISTRO INICIAL DE RAZAS ESPAÑOLAS,NaN,NaN,0505,0,11.57,0
5,REGISTRO INICIAL DEL RESTO DE RAZAS,NaN,NaN,0501,0,15.99,0
6,IMPRESO ALTA DE CAMADA,NaN,NaN,0601,0,1.15,0
7,FORMULARIO IDENTIFICACION (por cachorro al notificar nacimiento) RSCE,NaN,NaN,0103,0,2.75,0
8,FORMULARIO IDENTIFICACION (por cachorro al notificar nacimiento) EN ORIGEN,NaN,NaN,0104,0,1.98,0
9,INSCRIPCION CACHORRO,NaN,NaN,0105,0,9.01,0
10,RECARGO 100% (más de 6 meses y menos de 9) Art. 6.)13 Reglamento L.O.E.,NaN,NaN,0106,0,9.01,0
11,"RECARGO 200% (más de 9 meses, menos de 12) Art. 6.)13 Reglamento L.O.E.",NaN,NaN,0107,0,18.06,0
12,"EXCEPCION, RECARGO 300% (más de 12 meses y menos de 18) Art, 5.k) Reglamento L.O.E.",NaN,NaN,0108,0,27.06,0
13,INSCRIPCION IMPORTADOS,NaN,NaN,0101,0,20.02,0
14,INSCRIPCION DE OTROS LIBROS GENEALOGICOS (NO ADMITE PLUS DE URGENCIA),NaN,NaN,0102,0,29.75,0

In [20]:
df = pd.read_excel("data/2022/2022_TARIFAS_V1_1_Ago.xlsx")
df.head(15)

,Categoría,Trámite,Socios de la RSCE (€),Resto usuarios de la RSCE (€),Notas
0,INSCRIPCIONES,REGISTRO INICIAL RAZAS ESPAÑOLAS,25.0,25.0,Precio único
1,INSCRIPCIONES,REGISTRO INICIAL RESTO DE RAZAS,41.9,41.9,Precio único
2,INSCRIPCIONES,REGISTRO INICIAL GRUPO ÉTNICO,25.0,25.0,Precio único
3,INSCRIPCIONES,IMPRESO ALTA DE CAMADA,2.1,2.1,Precio único
4,INSCRIPCIONES,FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento),2.7,4.3,NaN
5,INSCRIPCIONES,INSCRIPCIÓN CACHORRO,14.9,18.0,NaN
6,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 6 meses y menos de 9 meses de edad,14.9,18.0,NaN
7,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 9 meses y menos de 12 meses de edad,29.8,36.0,NaN
8,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 12 meses y menos de 18 meses de edad,44.7,53.9,NaN
9,INSCRIPCIONES,INSCRIPCIÓN PERRO con más de 18 meses aportando prueba ADN progenitores y huella genética de compatibilidad,89.4,108.0,"Tramitación exclusiva oficinas RSCE, requiere autorización Comisión Libro de Orígenes Español"
10,INSCRIPCIONES,INSCRIPCIÓN IMPORTADOS,27.0,39.7,NaN
11,INSCRIPCIONES,INSCRIPCIÓN PERROS DE OTROS LIBROS GENEALÓGICOS,57.3,59.0,Este trámite no admite plus de urgencia
12,INSCRIPCIONES,DUPLICADO JUSTIFICANTE DE INSCRIPCIÓN,4.5,6.2,NaN
13,INSCRIPCIONES,BAJA DE UN PERRO EN EL LOE/RRC (para su posterior inscripción de otros libros genealógicos),27.0,39.7,NaN
14,INSCRIPCIONES,CONFIRMACIÓN DE RAZA (perros de razas españolas),5.1,5.1,Precio único

In [4]:
df = pd.read_excel("data/2022/2022_TARIFAS_V1_Feb.xlsx")
df.head(15)

,Categoría,Trámite,Socios de la RSCE (€),Resto usuarios de la RSCE (€),Notas
0,INSCRIPCIONES,REGISTRO INICIAL RAZAS ESPAÑOLAS,25.0,25.0,Precio único
1,INSCRIPCIONES,REGISTRO INICIAL RESTO DE RAZAS,41.9,41.9,Precio único
2,INSCRIPCIONES,REGISTRO INICIAL GRUPO ÉTNICO,25.0,25.0,Precio único
3,INSCRIPCIONES,IMPRESO ALTA DE CAMADA,2.1,2.1,Precio único
4,INSCRIPCIONES,FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento),2.7,4.3,NaN
5,INSCRIPCIONES,INSCRIPCIÓN CACHORRO,14.9,18.0,NaN
6,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 6 meses y menos de 9 meses de edad,14.9,18.0,NaN
7,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 9 meses y menos de 12 meses de edad,29.8,36.0,NaN
8,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 12 meses y menos de 18 meses de edad,44.7,53.9,NaN
9,INSCRIPCIONES,INSCRIPCIÓN PERRO con más de 18 meses aportando prueba ADN progenitores y huella genética de compatibilidad,89.4,108.0,"Tramitación exclusiva oficinas RSCE, requiere autorización Comisión Libro de Orígenes Español"
10,INSCRIPCIONES,INSCRIPCIÓN IMPORTADOS,27.0,39.7,NaN
11,INSCRIPCIONES,INSCRIPCIÓN PERROS DE OTROS LIBROS GENEALÓGICOS,57.3,59.0,Este trámite no admite plus de urgencia
12,INSCRIPCIONES,DUPLICADO JUSTIFICANTE DE INSCRIPCIÓN,4.5,6.2,NaN
13,INSCRIPCIONES,BAJA DE UN PERRO EN EL LOE/RRC (para su posterior inscripción de otros libros genealógicos),27.0,39.7,NaN
14,INSCRIPCIONES,CONFIRMACIÓN DE RAZA (perros de razas españolas),5.1,5.1,Precio único

In [5]:
df = pd.read_excel("data/2022/2022_TARIFAS_V3_Oct.xlsx")
df.head(15)

,Categoría,Trámite,Socios de la RSCE (€),Resto usuarios de la RSCE (€),Notas
0,INSCRIPCIONES,REGISTRO INICIAL RAZAS ESPAÑOLAS,26.3,26.3,Precio único
1,INSCRIPCIONES,REGISTRO INICIAL RESTO DE RAZAS,44.0,44.0,Precio único
2,INSCRIPCIONES,REGISTRO INICIAL GRUPO ÉTNICO,10.5,10.5,Precio único
3,INSCRIPCIONES,IMPRESO ALTA DE CAMADA,2.2,2.2,Precio único
4,INSCRIPCIONES,FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento),2.8,4.5,NaN
5,INSCRIPCIONES,INSCRIPCIÓN CACHORRO,15.6,18.9,NaN
6,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 6 meses y menos de 9 meses de edad,15.6,18.9,NaN
7,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 9 meses y menos de 12 meses de edad,31.2,37.8,NaN
8,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 12 meses y menos de 18 meses de edad,46.8,56.7,NaN
9,INSCRIPCIONES,INSCRIPCIÓN PERRO con más de 18 meses aportando prueba ADN progenitores y huella genética de compatibilidad,93.9,113.4,"Tramitación exclusiva oficinas RSCE, requiere autorización Comisión Libro de Orígenes Español"
10,INSCRIPCIONES,INSCRIPCIÓN IMPORTADOS,28.4,41.7,NaN
11,INSCRIPCIONES,INSCRIPCIÓN PERROS DE OTROS LIBROS GENEALÓGICOS,60.2,62.0,Este trámite no admite plus de urgencia
12,INSCRIPCIONES,DUPLICADO JUSTIFICANTE DE INSCRIPCIÓN,4.7,6.5,NaN
13,INSCRIPCIONES,BAJA DE UN PERRO EN EL LOE/RRC (para su posterior inscripción de otros libros genealógicos),28.4,41.7,NaN
14,INSCRIPCIONES,CONFIRMACIÓN DE RAZA (perros de razas españolas),5.4,5.4,Precio único

2023

In [6]:
df = pd.read_excel("data/2023/2023 IMPRESO COLABORADORAS V2023_1.xlsx")
df.head(15)

,SOCIEDAD CANINA,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,FECHA,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,TARIFA AÑO 2023,NaN,NaN,NaN,NaN
2,CONCEPTO,NaN,NaN,CÓDIGO,CANTIDAD,PRECIO,IMPORTE
3,INCRIPCIONES EN EL L.O.E./R.R.C.,NaN,NaN,NaN,NaN,NaN,NaN
4,REGISTRO INICIAL DE RAZAS ESPAÑOLAS,NaN,NaN,0505,0,11.57,0
5,REGISTRO INICIAL DEL RESTO DE RAZAS,NaN,NaN,0501,0,15.99,0
6,IMPRESO ALTA DE CAMADA,NaN,NaN,0601,0,1.15,0
7,FORMULARIO IDENTIFICACION (por cachorro al notificar nacimiento) RSCE,NaN,NaN,0103,0,2.75,0
8,FORMULARIO IDENTIFICACION (por cachorro al notificar nacimiento) EN ORIGEN,NaN,NaN,0104,0,1.98,0
9,INSCRIPCIÓN CACHORRO RAZAS ESPAÑOLAS BONIFICADAS ( Del 01/05/2023 al 30/04/2024),NaN,NaN,0113,NaN,4.51,0
10,INSCRIPCION CACHORRO,NaN,NaN,0105,0,9.01,0
11,RECARGO 100% (más de 6 meses y menos de 9) Art. 6.)13 Reglamento L.O.E.,NaN,NaN,0106,0,9.01,0
12,"RECARGO 200% (más de 9 meses, menos de 12) Art. 6.)13 Reglamento L.O.E.",NaN,NaN,0107,0,18.06,0
13,"EXCEPCION, RECARGO 300% (más de 12 meses y menos de 18) Art, 5.k) Reglamento L.O.E.",NaN,NaN,0108,0,27.06,0
14,INSCRIPCION IMPORTADOS,NaN,NaN,0101,0,20.02,0

In [7]:
df = pd.read_excel("data/2023/2023_TARIFAS.xlsx")
df.head(15)

,Categoría,Trámite,Socios de la RSCE (€),Resto usuarios de la RSCE (€),Notas
0,INSCRIPCIONES,REGISTRO INICIAL RAZAS ESPAÑOLAS,26.3,26.3,Precio único
1,INSCRIPCIONES,REGISTRO INICIAL RESTO DE RAZAS,44.0,44.0,Precio único
2,INSCRIPCIONES,REGISTRO INICIAL GRUPO ÉTNICO,10.5,10.5,Precio único
3,INSCRIPCIONES,IMPRESO ALTA DE CAMADA,2.2,2.2,Precio único
4,INSCRIPCIONES,FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento),2.8,4.5,NaN
5,INSCRIPCIONES,INSCRIPCIÓN CACHORRO,15.6,18.9,NaN
6,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 6 meses y menos de 9 meses de edad,15.6,18.9,NaN
7,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 9 meses y menos de 12 meses de edad,31.2,37.8,NaN
8,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 12 meses y menos de 18 meses de edad,46.8,56.7,NaN
9,INSCRIPCIONES,INSCRIPCIÓN PERRO con más de 18 meses aportando prueba ADN progenitores y huella genética de compatibilidad,93.9,113.4,"Tramitación exclusiva oficinas RSCE, requiere autorización Comisión Libro de Orígenes Español"
10,INSCRIPCIONES,INSCRIPCIÓN IMPORTADOS,28.4,41.7,NaN
11,INSCRIPCIONES,INSCRIPCIÓN PERROS PROCEDENTES DE OTROS LIBROS GENEALÓGICOS,28.4,41.7,Este trámite no admite plus de urgencia
12,INSCRIPCIONES,DUPLICADO JUSTIFICANTE DE INSCRIPCIÓN,4.7,6.5,NaN
13,INSCRIPCIONES,BAJA DE UN PERRO EN EL LOE/RRC (para su posterior inscripción de otros libros genealógicos),28.4,41.7,NaN
14,INSCRIPCIONES,CONFIRMACIÓN DE RAZA (perros de razas españolas),5.4,5.4,Precio único

2024

In [8]:
df = pd.read_excel("data/2024/2024 IMPRESO COLABORADORAS V3.xlsx")
df.head(15)

,SOCIEDAD CANINA,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,FECHA,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,TARIFA AÑO 2024,NaN,NaN,NaN,NaN
2,CONCEPTO,NaN,NaN,CÓDIGO,CANTIDAD,PRECIO,IMPORTE
3,INCRIPCIONES EN EL L.O.E./R.R.C.,NaN,NaN,NaN,NaN,NaN,NaN
4,REGISTRO INICIAL DE RAZAS ESPAÑOLAS,NaN,NaN,11600001,NaN,11.92,0
5,REGISTRO INICIAL DE RAZAS ESPAÑOLAS VULNERABLES,NaN,NaN,11600004,NaN,8.92,NaN
6,REGISTRO INICIAL DEL RESTO DE RAZAS,NaN,NaN,11600002,NaN,16.5,0
7,REGISTRO INICIAL GRUPO ÉTNICO,NaN,NaN,11600003,NaN,8.92,0
8,IMPRESO ALTA DE CAMADA,NaN,NaN,11800001,NaN,1.2,0
9,FORMULARIO IDENTIFICACION (por cachorro al notificar nacimiento) RSCE,NaN,NaN,11900001,NaN,2.85,0
10,FORMULARIO IDENTIFICACION (por cachorro al notificar nacimiento) EN ORIGEN,NaN,NaN,11900002,NaN,1.98,0
11,INSCRIPCIÓN CACHORRO RAZAS ESPAÑOLAS BONIFICADAS ( Del 01/05/2024 al 30/04/2025),NaN,NaN,11100004,NaN,4.63,0
12,INSCRIPCION CACHORRO,NaN,NaN,11100001,NaN,9.3,0
13,RECARGO 100% (más de 6 meses y menos de 9) Art. 6.)13 Reglamento L.O.E.,NaN,NaN,11400001,NaN,9.3,0
14,"RECARGO 200% (más de 9 meses, menos de 12) Art. 6.)13 Reglamento L.O.E.",NaN,NaN,11400002,NaN,18.59,0

In [9]:
df = pd.read_excel("data/2024/2024_TARIFAS.xlsx")
df.head(15)

,Categoría,Trámite,Socios de la RSCE (€),Resto usuarios de la RSCE (€),Notas
0,INSCRIPCIONES,REGISTRO INICIAL RAZAS ESPAÑOLAS,27.1,27.1,Precio único
1,INSCRIPCIONES,REGISTRO INICIAL RAZAS ESPAÑOLAS VULNERABLES,10.8,10.8,Precio único; nueva categoría introducida en 2024
2,INSCRIPCIONES,REGISTRO INICIAL RESTO DE RAZAS,45.4,45.4,Precio único
3,INSCRIPCIONES,REGISTRO INICIAL GRUPO ÉTNICO,10.8,10.8,Precio único
4,INSCRIPCIONES,IMPRESO ALTA DE CAMADA,2.3,2.3,Precio único
5,INSCRIPCIONES,FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento),2.9,4.6,NaN
6,INSCRIPCIONES,INSCRIPCIÓN CACHORRO,16.1,19.5,NaN
7,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 6 meses y menos de 9 meses de edad,16.1,19.5,NaN
8,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 9 meses y menos de 12 meses de edad,32.2,39.0,NaN
9,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 12 meses y menos de 18 meses de edad,48.3,58.5,NaN
10,INSCRIPCIONES,INSCRIPCIÓN PERRO con más de 18 meses aportando prueba ADN progenitores y huella genética de compatibilidad,96.8,116.9,"Tramitación exclusiva oficinas RSCE, requiere autorización Comisión Libro de Orígenes Español"
11,INSCRIPCIONES,INSCRIPCIÓN CACHORRO DE RAZAS ESPAÑOLAS BONIFICADAS,8.0,9.7,Nuevo trámite introducido en 2024
12,INSCRIPCIONES,INSCRIPCIÓN CACHORRO EN EL REGISTRO DE GRUPOS ÉTNICOS,8.0,8.0,Nuevo trámite introducido en 2024; precio único indicado igual en ambas columnas en el documento original
13,INSCRIPCIONES,INSCRIPCIÓN IMPORTADOS,29.3,43.0,NaN
14,INSCRIPCIONES,INSCRIPCIÓN PERROS PROCEDENTES DE OTROS LIBROS GENEALÓGICOS,29.3,43.0,Este trámite no admite plus de urgencia

2025

In [10]:
df = pd.read_excel("data/2025/2025 IMPRESO COLABORADORAS v2.xlsx")
df.head(15)

,SOCIEDAD CANINA,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,FECHA,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,TARIFA AÑO 2025,NaN,NaN,NaN,NaN
2,CONCEPTO,NaN,NaN,CÓDIGO,CANTIDAD,PRECIO,IMPORTE
3,INCRIPCIONES EN EL L.O.E./R.R.C.,NaN,NaN,NaN,NaN,NaN,NaN
4,REGISTRO INICIAL DE RAZAS ESPAÑOLAS,NaN,NaN,11600001,NaN,12.54,0
5,REGISTRO INICIAL DE RAZAS ESPAÑOLAS VULNERABLES,NaN,NaN,11600004,NaN,9.33,0
6,REGISTRO INICIAL DEL RESTO DE RAZAS,NaN,NaN,11600002,NaN,23.62,0
7,REGISTRO INICIAL GRUPO ÉTNICO,NaN,NaN,11600003,NaN,9.33,0
8,IMPRESO ALTA DE CAMADA,NaN,NaN,11800001,NaN,1.25,0
9,FORMULARIO IDENTIFICACION (por cachorro al notificar nacimiento) RSCE,NaN,NaN,11900001,NaN,2.97,0
10,FORMULARIO IDENTIFICACION (por cachorro al notificar nacimiento) EN ORIGEN,NaN,NaN,11900002,0,2.07,0
11,INSCRIPCIÓN CACHORRO RAZAS ESPAÑOLAS BONIFICADAS ( Del 01/05/2024 al 30/04/2025),NaN,NaN,11100004,NaN,4.87,0
12,INSCRIPCION CACHORRO,NaN,NaN,11100001,NaN,9.78,0
13,RECARGO 100% (más de 6 meses y menos de 9) Art. 6.)13 Reglamento L.O.E.,NaN,NaN,11400001,0,9.78,0
14,"RECARGO 200% (más de 9 meses, menos de 12) Art. 6.)13 Reglamento L.O.E.",NaN,NaN,11400002,0,19.54,0

In [11]:
df = pd.read_excel("data/2025/2025 IMPRESO COLABORADORAS v4.xlsx")
df.head(15)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SOCIEDAD CANINA,NaN,NaN,NaN,NaN,NaN,NaN
2,FECHA,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,TARIFA AÑO 2025 (desde 15/09/2025),NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CONCEPTO,NaN,NaN,CÓDIGO,CANTIDAD,PRECIO,IMPORTE
6,INCRIPCIONES EN EL L.O.E./R.R.C.,NaN,NaN,NaN,NaN,NaN,NaN
7,REGISTRO INICIAL DE RAZAS ESPAÑOLAS,NaN,NaN,11600001,0,12.54,0
8,REGISTRO INICIAL DE RAZAS ESPAÑOLAS VULNERABLES,NaN,NaN,11600004,0,9.33,0
9,REGISTRO INICIAL DEL RESTO DE RAZAS,NaN,NaN,11600002,0,23.62,0
10,REGISTRO INICIAL GRUPO ÉTNICO,NaN,NaN,11600003,0,9.33,0
11,IMPRESO ALTA DE CAMADA,NaN,NaN,11800001,0,1.25,0
12,INSCRIPCION IMPORTADOS,NaN,NaN,11100002,0,21.71,0
13,INSCRIPCION DE OTROS LIBROS GENEALOGICOS (NO ADMITE PLUS DE URGENCIA),NaN,NaN,11100003,0,21.71,0
14,DUPLICADO JUSTIFICANTE DE INSCRIPCION,NaN,NaN,12000001,0,5.8,0

In [12]:
df = pd.read_excel("data/2025/2025_TARIFAS_V3_Ene.xlsx")
df.head(15)

,Categoría,Trámite,Socios de la RSCE (€),Resto usuarios de la RSCE (€),Notas
0,INSCRIPCIONES,REGISTRO INICIAL RAZAS ESPAÑOLAS,28.5,28.5,Precio único
1,INSCRIPCIONES,REGISTRO INICIAL RAZAS ESPAÑOLAS VULNERABLES,11.3,11.3,Precio único
2,INSCRIPCIONES,REGISTRO INICIAL RESTO DE RAZAS,65.0,65.0,Precio único
3,INSCRIPCIONES,REGISTRO INICIAL GRUPO ÉTNICO,11.3,11.3,Precio único
4,INSCRIPCIONES,IMPRESO ALTA DE CAMADA,2.4,2.4,Precio único
5,INSCRIPCIONES,FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento),3.0,4.8,NaN
6,INSCRIPCIONES,INSCRIPCIÓN CACHORRO,16.9,20.5,NaN
7,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 6 meses y menos de 9 meses de edad,16.9,20.5,NaN
8,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 9 meses y menos de 12 meses de edad,33.8,41.0,NaN
9,INSCRIPCIONES,RECARGO POR INSCRIPCIÓN DE CACHORRO con más de 12 meses y menos de 18 meses de edad,50.7,61.5,NaN
10,INSCRIPCIONES,INSCRIPCIÓN PERRO con más de 18 meses aportando prueba ADN progenitores y huella genética de compatibilidad,101.6,122.7,"Tramitación exclusiva oficinas RSCE, requiere autorización Comisión Libro de Orígenes Español"
11,INSCRIPCIONES,INSCRIPCIÓN CACHORRO DE RAZAS ESPAÑOLAS BONIFICADAS,8.8,10.2,NaN
12,INSCRIPCIONES,INSCRIPCIÓN CACHORRO EN EL REGISTRO DE GRUPOS ÉTNICOS,8.4,8.4,NaN
13,INSCRIPCIONES,INSCRIPCIÓN IMPORTADOS,30.8,45.2,NaN
14,INSCRIPCIONES,INSCRIPCIÓN PERROS PROCEDENTES DE OTROS LIBROS GENEALÓGICOS,30.8,45.2,Este trámite no admite plus de urgencia

In [13]:
df = pd.read_excel("data/2025/2025_TARIFAS_V4_Sept.xlsx")
df.head(15)

,Categoría,Trámite,Socios de la RSCE (€),Resto usuarios de la RSCE (€),Notas
0,INSCRIPCIONES,REGISTRO INICIAL RAZAS ESPAÑOLAS,28.5,28.5,Precio único
1,INSCRIPCIONES,REGISTRO INICIAL RAZAS ESPAÑOLAS VULNERABLES,11.3,11.3,Precio único
2,INSCRIPCIONES,REGISTRO INICIAL RESTO DE RAZAS,65.0,65.0,Precio único
3,INSCRIPCIONES,REGISTRO INICIAL GRUPO ÉTNICO,11.3,11.3,Precio único
4,INSCRIPCIONES,IMPRESO ALTA DE CAMADA,2.4,2.4,Precio único
5,INSCRIPCIONES,FORMULARIO IDENTIFICACIÓN (por cachorro al notificar nacimiento),3.0,4.8,NaN
6,INSCRIPCIONES ACCESS LBO/RBR,INSCRIPCIÓN CACHORRO ACCESS LBO/RBR,11.0,15.0,Nueva estructura de niveles de pedigree (Access/Premium/Plus) introducida en V4 (sept 2025)
7,INSCRIPCIONES ACCESS LBO/RBR,RECARGO POR INSCRIPCIÓN DE CACHORRO ACCESS LBO/RBR con más de 6 meses y menos de 9 meses de edad,11.0,15.0,NaN
8,INSCRIPCIONES ACCESS LBO/RBR,RECARGO POR INSCRIPCIÓN DE CACHORRO ACCESS LBO/RBR con más de 9 meses y menos de 12 meses de edad,22.0,30.0,NaN
9,INSCRIPCIONES ACCESS LBO/RBR,RECARGO POR INSCRIPCIÓN DE CACHORRO ACCESS LBO/RBR con más de 12 meses y menos de 18 meses de edad,33.0,45.0,NaN
10,INSCRIPCIONES PREMIUM LOE/RRC,INSCRIPCIÓN CACHORRO PREMIUM LOE/RRC,16.9,20.5,Nueva estructura de niveles de pedigree (Access/Premium/Plus) introducida en V4 (sept 2025)
11,INSCRIPCIONES PREMIUM LOE/RRC,RECARGO POR INSCRIPCIÓN DE CACHORRO PREMIUM LOE/RRC con más de 6 meses y menos de 9 meses de edad,16.9,20.5,NaN
12,INSCRIPCIONES PREMIUM LOE/RRC,RECARGO POR INSCRIPCIÓN DE CACHORRO PREMIUM LOE/RRC con más de 9 meses y menos de 12 meses de edad,33.8,41.0,NaN
13,INSCRIPCIONES PREMIUM LOE/RRC,RECARGO POR INSCRIPCIÓN DE CACHORRO PREMIUM LOE/RRC con más de 12 meses y menos de 18 meses de edad,50.7,61.5,NaN
14,INSCRIPCIONES PREMIUM LOE/RRC,INSCRIPCIÓN PERRO con más de 18 meses aportando prueba ADN progenitores y huella genética de compatibilidad,101.6,122.7,"Tramitación exclusiva oficinas RSCE, requiere autorización Comisión Libro de Orígenes Español"

2026

In [15]:
df = pd.read_excel("data/2026/2026 IMPRESO COLABORADORAS v3.xlsx")
df.head(15)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SOCIEDAD CANINA,NaN,NaN,NaN,NaN,NaN,NaN
2,FECHA,NaN,NaN,NaN,NaN,NaN,NaN
3,TARIFA AÑO 2026 (en vigor desde el 1 de Julio de 2026),NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,CONCEPTO,NaN,NaN,CÓDIGO,CANTIDAD,PRECIO,IMPORTE
6,INCRIPCIONES EN EL L.O.E./R.R.C.,NaN,NaN,NaN,NaN,NaN,NaN
7,REGISTRO INICIAL DE RAZAS ESPAÑOLAS,NaN,NaN,11600001,NaN,12.54,0
8,REGISTRO INICIAL DE RAZAS ESPAÑOLAS VULNERABLES,NaN,NaN,11600004,NaN,9.33,0
9,REGISTRO INICIAL DEL RESTO DE RAZAS,NaN,NaN,11600002,NaN,25.44,0
10,REGISTRO INICIAL GRUPO ÉTNICO,NaN,NaN,11600003,NaN,9.33,0
11,IMPRESO ALTA DE CAMADA (PERROS DE RAZA),NaN,NaN,11800001,NaN,1.78,0
12,IMPRESO ALTA DE CAMADA (GRUPOS ÉTNICOS),NaN,NaN,11800002,NaN,1.78,0
13,INSCRIPCION IMPORTADOS,NaN,NaN,11100002,NaN,23.54,0
14,INSCRIPCION DE OTROS LIBROS GENEALOGICOS (NO ADMITE PLUS DE URGENCIA),NaN,NaN,11100003,NaN,23.54,0

In [16]:
df = pd.read_excel("data/2026/2026 TARIFAS V2.xlsx")
df.head(15)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Real Sociedad Canina de España,NaN,NaN,NaN,NaN
1,-Desde 1911-,NaN,NaN,NaN,NaN
2,TARIFA GENERAL DE PRECIOS,NaN,NaN,NaN,NaN
3,(En vigor desde el día 1 de febrero de 2026),NaN,NaN,NaN,NaN
4,El pago de los trámites podrá realizarse:,NaN,NaN,NaN,NaN
5,· Mediante transferencia bancaria o ingreso en la cuenta corriente abierta a nombre de la REAL SOCIEDAD CANINA DE ESPAÑA:,NaN,NaN,NaN,NaN
6,ENTIDAD,BANCO SANTANDER,NaN,NaN,NaN
7,NÚMERO DE CUENTA,ES32 0030 8269 3800 0027 4271,CÓDIGO BIC (para pagos desde el extranjero),BSCHESMM,NaN
8,· Únicamente se admitirán pagos en efectivo en las tramitaciones que se realicen de forma presencial en nuestras oficinas,NaN,NaN,NaN,NaN
9,TRÁMITES,NaN,NaN,Socios de la RSCE,Resto usuarios de la RSCE
10,INSCRIPCIONES,NaN,NaN,NaN,NaN
11,REGISTRO INICIAL RAZAS ESPAÑOLAS,NaN,NaN,28.5,NaN
12,REGISTRO INICIAL RAZAS ESPAÑOLAS VULNERABLES,NaN,NaN,11.3,NaN
13,REGISTRO INICIAL RESTO DE RAZAS,NaN,NaN,70,NaN
14,REGISTRO INICIAL GRUPO ÉTNICO,NaN,NaN,11.3,NaN